//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SousChef.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryShoppingList
    {
        public int id { get; set; }
        public int inventoryId { get; set; }
        public int itemId { get; set; }
        public int inventoryUserId { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual InventoryUser InventoryUser { get; set; }
        public virtual Item Item { get; set; }
    }
}
