//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SousChef.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItem
    {
        public Nullable<int> id { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public int itemId { get; set; }
        public string itemDescription { get; set; }
        public string upc { get; set; }
        public bool isPerishable { get; set; }
        public Nullable<int> expiration { get; set; }
        public string image { get; set; }
    }
}
