//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SousChef.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryUser
    {
        public InventoryUser()
        {
            this.InventoryUserSources = new HashSet<InventoryUserSource>();
        }
    
        public int id { get; set; }
        public int inventoryId { get; set; }
        public string displayName { get; set; }
        public string email { get; set; }
        public bool isVerified { get; set; }
        public string phoneNumber { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual ICollection<InventoryUserSource> InventoryUserSources { get; set; }
    }
}
