//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SousChef.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public Receipt()
        {
            this.ReceiptItems = new HashSet<ReceiptItem>();
        }
    
        public int id { get; set; }
        public int inventoryUserSourceId { get; set; }
        public System.DateTime timestamp { get; set; }
    
        public virtual InventoryUserSource InventoryUserSource { get; set; }
        public virtual ICollection<ReceiptItem> ReceiptItems { get; set; }
    }
}
