//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SousChef.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Source
    {
        public Source()
        {
            this.InventoryUserSources = new HashSet<InventoryUserSource>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<InventoryUserSource> InventoryUserSources { get; set; }
    }
}
